/**
 * generator/barrel.ts
 * index.ts barrel 파일 생성
 *
 * 출력 예시:
 * // Generated by figma-to-react
 * export { Button } from './Button';
 * export type { ButtonProps } from './Button';
 * export { Card } from './Card';
 * export type { CardProps } from './Card';
 */

// ─── 타입 ─────────────────────────────────────────────────────────────────────

export interface BarrelEntry {
  componentName: string;
  /** 파일 경로 (확장자 없음) */
  filePath: string;
  /** Props 타입도 export할지 여부 */
  exportTypes?: boolean;
}

// ─── barrel 파일 생성 ─────────────────────────────────────────────────────────

export function generateBarrelFile(entries: BarrelEntry[]): string {
  if (entries.length === 0) {
    return '// Generated by figma-to-react — no components found\n';
  }

  const lines: string[] = [
    '// Generated by figma-to-react — Do not edit manually',
    '',
  ];

  for (const entry of entries) {
    lines.push(`export { ${entry.componentName} } from '${entry.filePath}';`);
    if (entry.exportTypes !== false) {
      lines.push(`export type { ${entry.componentName}Props } from '${entry.filePath}';`);
    }
  }

  lines.push('');
  return lines.join('\n');
}

// ─── 카테고리별 barrel (폴더 구조용) ─────────────────────────────────────────

/**
 * 컴포넌트를 카테고리(폴더)별로 분류하여 각 폴더의 index.ts 생성
 */
export function generateCategoryBarrels(
  entries: BarrelEntry[],
  categoryGetter: (entry: BarrelEntry) => string,
): Map<string, string> {
  const categories = new Map<string, BarrelEntry[]>();

  for (const entry of entries) {
    const cat = categoryGetter(entry);
    if (!categories.has(cat)) categories.set(cat, []);
    categories.get(cat)!.push(entry);
  }

  const result = new Map<string, string>();
  for (const [cat, catEntries] of categories) {
    result.set(cat, generateBarrelFile(catEntries));
  }
  return result;
}

// ─── README.md 생성 (컴포넌트 목록 문서) ─────────────────────────────────────

export function generateComponentReadme(entries: BarrelEntry[]): string {
  const lines: string[] = [
    '# Generated Components',
    '',
    '> Auto-generated by figma-to-react. Do not edit manually.',
    '',
    '## Components',
    '',
  ];

  for (const entry of entries) {
    lines.push(`### \`${entry.componentName}\``);
    lines.push(`- File: \`${entry.filePath}.tsx\``);
    lines.push(`- Props: \`${entry.componentName}Props\``);
    lines.push('');
  }

  return lines.join('\n');
}
