/**
 * generator/types-gen.ts
 * IRPropDef[] → TypeScript interface / type 문자열 생성
 *
 * 출력 예시:
 * export interface ButtonProps {
 *   state?: 'default' | 'hover' | 'pressed';
 *   size?: 'small' | 'medium' | 'large';
 *   label?: string;
 *   disabled?: boolean;
 * }
 */

import type { IRPropDef } from '../ir/types.js';

// ─── 인터페이스 생성 ─────────────────────────────────────────────────────────

/**
 * Props 배열 → TypeScript interface 문자열
 * @param componentName - PascalCase 컴포넌트 이름
 * @param props - IRPropDef[]
 * @param includeChildren - children prop 추가 여부
 */
export function generatePropsInterface(
  componentName: string,
  props: IRPropDef[],
  includeChildren = false,
): string {
  const propLines: string[] = [];

  for (const prop of props) {
    const tsType = propDefToTsType(prop);
    const optional = prop.defaultValue !== undefined ? '?' : '?';
    const comment = prop.description ? `  /** ${prop.description} */\n` : '';
    propLines.push(`${comment}  ${prop.name}${optional}: ${tsType};`);
  }

  if (includeChildren) {
    propLines.push('  children?: React.ReactNode;');
  }

  // 항상 className 허용 (합성 패턴)
  propLines.push('  className?: string;');

  const body = propLines.join('\n');
  return [
    `export interface ${componentName}Props {`,
    body,
    `}`,
  ].join('\n');
}

// ─── PropDef → TypeScript 타입 ────────────────────────────────────────────────

export function propDefToTsType(prop: IRPropDef): string {
  switch (prop.type) {
    case 'boolean':
      return 'boolean';

    case 'string':
      return 'string';

    case 'enum': {
      if (!prop.values || prop.values.length === 0) return 'string';
      return prop.values.map(v => `'${v}'`).join(' | ');
    }

    case 'node':
      return 'React.ReactNode';

    default:
      return 'unknown';
  }
}

// ─── 기본 Props (Variant 없는 컴포넌트용) ────────────────────────────────────

/**
 * Variant 정보 없을 때 기본 props interface 생성
 */
export function generateDefaultPropsInterface(componentName: string): string {
  return [
    `export interface ${componentName}Props {`,
    `  className?: string;`,
    `  children?: React.ReactNode;`,
    `}`,
  ].join('\n');
}

// ─── 여러 컴포넌트 타입 모음 파일 생성 ───────────────────────────────────────

export function generateTypesFile(
  components: Array<{ name: string; props: IRPropDef[]; hasChildren: boolean }>,
): string {
  const lines: string[] = [
    `// Generated by figma-to-react — Do not edit manually`,
    `import type React from 'react';`,
    ``,
  ];

  for (const comp of components) {
    if (comp.props.length > 0) {
      lines.push(generatePropsInterface(comp.name, comp.props, comp.hasChildren));
    } else {
      lines.push(generateDefaultPropsInterface(comp.name));
    }
    lines.push('');
  }

  return lines.join('\n');
}
