/**
 * theme/generator.ts
 * DesignTokens → theme.ts (공용 테마 파일) 생성
 *
 * 출력: theme.ts — styled-components ThemeProvider, CSS Variables, Tailwind Config 확장에 사용
 */

import type { DesignTokens } from '../ir/types.js';

// ─── theme.ts 생성 ───────────────────────────────────────────────────────────

/**
 * DesignTokens → theme.ts 파일 내용
 */
export function generateThemeFile(tokens: DesignTokens): string {
  const sections: string[] = [
    '// Generated by figma-to-react — Do not edit manually',
    '',
    `export const theme = {`,
    `  colors: ${JSON.stringify(tokens.colors, null, 4)},`,
    '',
    `  typography: ${JSON.stringify(tokens.typography, null, 4)},`,
    '',
    `  spacing: ${JSON.stringify(tokens.spacing, null, 4)},`,
    '',
    `  borderRadius: ${JSON.stringify(tokens.borderRadius, null, 4)},`,
    '',
    `  shadows: ${JSON.stringify(tokens.shadows, null, 4)},`,
    '',
    `  breakpoints: ${JSON.stringify(tokens.breakpoints, null, 4)},`,
    `} as const;`,
    '',
    `export type Theme = typeof theme;`,
    '',
    '// Styled-components 타입 확장',
    "declare module 'styled-components' {",
    '  export interface DefaultTheme extends Theme {}',
    '}',
  ];

  return sections.join('\n');
}

// ─── CSS 변수 파일 생성 ───────────────────────────────────────────────────────

/**
 * DesignTokens → CSS 커스텀 프로퍼티 파일 (:root 선언)
 * 예: --color-primary-500: #3B82F6;
 */
export function generateCssVariablesFile(tokens: DesignTokens): string {
  const lines: string[] = ['/* Generated by figma-to-react */', ':root {'];

  // Colors
  for (const [group, shades] of Object.entries(tokens.colors)) {
    for (const [shade, value] of Object.entries(shades)) {
      const varName = shade === 'DEFAULT'
        ? `--color-${group}`
        : `--color-${group}-${shade}`;
      lines.push(`  ${varName}: ${value};`);
    }
  }

  // Spacing
  for (const [key, value] of Object.entries(tokens.spacing)) {
    lines.push(`  --spacing-${key}: ${value}px;`);
  }

  // Border Radius
  for (const [key, value] of Object.entries(tokens.borderRadius)) {
    const k = key === 'DEFAULT' ? 'base' : key;
    lines.push(`  --radius-${k}: ${value}px;`);
  }

  // Typography
  for (const [name, style] of Object.entries(tokens.typography)) {
    lines.push(`  --font-family-${name}: '${style.fontFamily}', sans-serif;`);
    lines.push(`  --font-size-${name}: ${style.fontSize}px;`);
    lines.push(`  --font-weight-${name}: ${style.fontWeight};`);
    lines.push(`  --line-height-${name}: ${style.lineHeight};`);
  }

  lines.push('}');
  return lines.join('\n');
}

// ─── TypeScript 타입 생성 ────────────────────────────────────────────────────

/**
 * DesignTokens → TypeScript 타입 정의 파일
 * 자동완성 지원용 정확한 리터럴 타입 생성
 */
export function generateTokenTypes(tokens: DesignTokens): string {
  const lines: string[] = [
    '// Generated by figma-to-react — Do not edit manually',
    '',
  ];

  // Color key union
  const colorKeys: string[] = [];
  for (const [group, shades] of Object.entries(tokens.colors)) {
    for (const shade of Object.keys(shades)) {
      const key = shade === 'DEFAULT' ? group : `${group}-${shade}`;
      colorKeys.push(`'${key}'`);
    }
  }
  lines.push(`export type ColorToken = ${colorKeys.join(' | ') || 'never'};`);

  // Spacing key union
  const spacingKeys = Object.keys(tokens.spacing).map(k => `'${k}'`);
  lines.push(`export type SpacingToken = ${spacingKeys.join(' | ') || 'never'};`);

  // Typography key union
  const typographyKeys = Object.keys(tokens.typography).map(k => `'${k}'`);
  lines.push(`export type TypographyToken = ${typographyKeys.join(' | ') || 'never'};`);

  lines.push('');
  lines.push('export interface DesignTokenTypes {');
  lines.push('  color: ColorToken;');
  lines.push('  spacing: SpacingToken;');
  lines.push('  typography: TypographyToken;');
  lines.push('}');

  return lines.join('\n');
}
