import { describe, it, expect } from 'vitest';
import { ImportResolver } from '../../generator/import-resolver.js';
import {
  generateBarrelFile,
  generateComponentReadme,
  type BarrelEntry,
} from '../../generator/barrel.js';
import { basicFormat, addGenerationComment } from '../../generator/formatter.js';
import { TailwindAdapter } from '../../adapters/tailwind.js';
import { parseNode } from '../../parser/node-parser.js';
import type { FigmaNode } from '../../parser/figma-client.js';

const adapter = new TailwindAdapter();

function makeNode(overrides: Partial<FigmaNode> = {}): FigmaNode {
  return {
    id: '1:1',
    name: 'Button',
    type: 'COMPONENT',
    absoluteBoundingBox: { x: 0, y: 0, width: 100, height: 40 },
    ...overrides,
  };
}

// ─── ImportResolver ───────────────────────────────────────────────────────────

describe('ImportResolver', () => {
  it('기본 타입 import 포함', () => {
    const ir = parseNode(makeNode());
    const resolver = new ImportResolver(adapter);
    const result = resolver.resolve(ir, 'Button');
    const str = result.toString();
    expect(str).toContain("import type");
    expect(str).toContain('ButtonProps');
  });

  it('버튼 태그 → useState import', () => {
    const ir = parseNode(makeNode({
      type: 'FRAME',
      name: 'Button Container',
      children: [
        makeNode({ id: '1:2', name: 'Btn', type: 'FRAME' }),
      ],
    }));
    // 버튼 태그 추론을 위해 이름에 button 포함
    const buttonNode = parseNode(makeNode({ name: 'Submit Button', type: 'FRAME' }));
    const resolver = new ImportResolver(adapter);
    const result = resolver.resolve(buttonNode, 'SubmitButton');
    // import 문자열에서 useState 체크 (버튼 태그 감지 시)
    expect(result.declarations).toBeDefined();
  });

  it('INSTANCE → 컴포넌트 import 추가', () => {
    const instanceNode = parseNode(makeNode({
      type: 'INSTANCE',
      name: 'Icon',
      componentId: 'icon-comp-id',
    }));
    const resolver = new ImportResolver(adapter);
    const result = resolver.resolve(instanceNode, 'Card');
    const decls = result.declarations;
    const iconImport = decls.find(d => d.source.includes('Icon'));
    expect(iconImport).toBeDefined();
  });

  it('정렬 순서: 외부 패키지 → 상대 경로', () => {
    const ir = parseNode(makeNode());
    const resolver = new ImportResolver(adapter);
    const result = resolver.resolve(ir, 'Button');
    const sources = result.declarations.map(d => d.source);
    // react 계열이 앞에, ./types 가 뒤에 오는지 확인
    const typeIdx = sources.findIndex(s => s.includes('./types'));
    const reactIdx = sources.findIndex(s => s === 'react');
    if (reactIdx !== -1 && typeIdx !== -1) {
      expect(reactIdx).toBeLessThan(typeIdx);
    }
  });
});

// ─── generateBarrelFile ───────────────────────────────────────────────────────

describe('generateBarrelFile', () => {
  const entries: BarrelEntry[] = [
    { componentName: 'Button', filePath: './Button/Button' },
    { componentName: 'Card', filePath: './Card/Card' },
    { componentName: 'Input', filePath: './Input/Input' },
  ];

  it('export 구문 포함', () => {
    const barrel = generateBarrelFile(entries);
    expect(barrel).toContain("export { Button } from './Button/Button';");
    expect(barrel).toContain("export { Card } from './Card/Card';");
  });

  it('Props 타입 export 포함', () => {
    const barrel = generateBarrelFile(entries);
    expect(barrel).toContain("export type { ButtonProps }");
    expect(barrel).toContain("export type { CardProps }");
  });

  it('생성 주석 포함', () => {
    const barrel = generateBarrelFile(entries);
    expect(barrel).toContain('Generated by figma-to-react');
  });

  it('빈 entries → 기본 주석만', () => {
    const barrel = generateBarrelFile([]);
    expect(barrel).toContain('no components found');
  });
});

// ─── generateComponentReadme ──────────────────────────────────────────────────

describe('generateComponentReadme', () => {
  it('마크다운 헤딩 포함', () => {
    const readme = generateComponentReadme([
      { componentName: 'Button', filePath: './Button' },
    ]);
    expect(readme).toContain('# Generated Components');
    expect(readme).toContain('### `Button`');
  });
});

// ─── basicFormat ─────────────────────────────────────────────────────────────

describe('basicFormat', () => {
  it('연속 빈 줄 → 최대 1개', () => {
    const input = 'line1\n\n\n\nline2';
    const result = basicFormat(input);
    expect(result).not.toContain('\n\n\n');
    expect(result).toContain('line1');
    expect(result).toContain('line2');
  });

  it('파일 끝 개행 보장', () => {
    const result = basicFormat('const x = 1;');
    expect(result.endsWith('\n')).toBe(true);
  });

  it('JSON 포맷팅', () => {
    const result = basicFormat('{"a":1,"b":2}', 'json');
    expect(result).toContain('  "a": 1');
    expect(result.endsWith('\n')).toBe(true);
  });

  it('잘못된 JSON → 원본 반환', () => {
    const input = '{ invalid json }';
    const result = basicFormat(input, 'json');
    expect(result).toBe(input);
  });
});

// ─── addGenerationComment ─────────────────────────────────────────────────────

describe('addGenerationComment', () => {
  it('기본 주석 추가', () => {
    const code = 'export const x = 1;';
    const result = addGenerationComment(code);
    expect(result).toContain('Generated by figma-to-react');
    expect(result).toContain('export const x = 1;');
  });

  it('figmaFile 포함 시 Source 줄 추가', () => {
    const result = addGenerationComment('const x = 1;', { figmaFile: 'Design.fig' });
    expect(result).toContain('Source: Design.fig');
  });

  it('커스텀 editNote', () => {
    const result = addGenerationComment('const x = 1;', { editNote: 'DO NOT TOUCH' });
    expect(result).toContain('DO NOT TOUCH');
  });
});
